time_window:
  since: "24h"
fetcher:
  sources_path: "sources.json"
  min_chars: 100
  max_per_source: 1000
  concurrency: 8
  timeout: 30
  user_agent: "market-radar/1.0"
  feed_retries: 2
density:
  model_id: "BAAI/bge-m3"
  model_cache_dir: null
  title_score: 0.7
  content_score: 0.3
  content_chars: 300
  batch_size: 64
  window_hours: 24
  deduplicate: true
  deduplication_threshold: 0.92
summarizer:
  model: "openrouter/auto"
  temperature: 0.2
  timeout: 60
  api_key: null
  fallback_summary: true
hotness:
  weights:
    time: 0.4
    density: 0.3
    domain: 0.3
  time_decay: 4.0
output:
  path: "output/news_hotness.json"
